### ISSUE TITLE
Why not add the AT24C32 and AT24C64 to the library?

### ISSUE THREAD

**Issue by floatAsNeeded** [stefangs/arduino-library-at24cxxx#3]
Why not add to the library also the c32 and c64?

I tried with this H file and seems to work good with the example code. Just changed the size of the eeprom and the page size to 32

```
#ifndef AT24C32_H
#define AT24C32_H

#include "at24cxxx.h"

class AT24C32 : public AT24Cxxx {

  public:
    AT24C32(uint8_t address, TwoWire& i2c = Wire, uint8_t writeDelay = 6) :
      AT24Cxxx(address, i2c, writeDelay, 4096, 32) {}
};

#endif
```

Can be also updated the keyword file

AT24C32	KEYWORD3

Same thing can be done for the at24C64 but only with 8192 size

**Comment by stefangs** [comment]
I have now merged you pull request with the support for the chips and released as 1.1.0, Thanks a lot for the contribution and sorry I was so slow on merging - I appreciate the help!
